version: '3.4'
services:
  node-app:
    build: .
    command: nodemon --inspect=0.0.0.0:9229 /node/server.js 3000
    volumes:
      - .:/node
      - /node/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
